env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - standard-with-typescript
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: ./tsconfig.json
  extraFileExtensions:
    - .vue
plugins:
  - vue
  - '@typescript-eslint'
overrides:
  - files:
      - src/**/*.js
  - files:
      - src/**/*.ts
      - src/**/*.vue
    rules:
      # TypeScript-specific rules
      '@typescript-eslint/explicit-function-return-type': warn
      '@typescript-eslint/quotes': [ warn, double, avoid-escape ]
rules:
  # Vue-related rules
  vue/singleline-html-element-content-newline: off
  vue/multi-word-component-names: off
  vue/no-unused-components: warn
  vue/max-attributes-per-line:
    - warn
    - singleline:
        max: 5
      multiline:
        max: 1
  # General ECMAScript rules
  no-unused-vars: warn
  quotes: [ warn, double, avoid-escape ]
